config/routes.rb
Hogwarts::Application.routes.draw do
 
root "house#index"
resource :house, only: [:index, :show]
resources :students, only: [:index, :show]

end

app/models/houses.rb
class House < ActiveRecord::Base
end

app/models/student.rb
def Student < ActiveRecord::Base
  belongs_to :house
end

app/controllers/StudentController.rb
class StudentsController < ActionController

  def index
  end

  def show
    @student = Student.find(:id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = Houses.all
  end

  def show
    @houses = Houses.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/index.html.erb
<h1>The houses</h1>
<% houses.each do |house| %>
  <div class="house">
    <h2><a href="houses_path"</a>@house</h2>
    <img src="<% house.image_url %>"/>
  <div>
<% end %>

app/views/houses/show.html.erb
<h1><%= @house.name %></h1>
<% @house.students.each do |student| %>
<div class="student">
  <h2><%= student.name %></h2>
  <%= image_tag student.img_url %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html
<html>
<head>
  <title>Hogwarts</title
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <h1>Welcome to Hogwarts!</h1>
    <h2><a href="/houses">View Houses</a> | <a href="/students">View Students</a> | <a href="/students/new">Enroll</a></h2>
  </nav>

  <%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Here are the students</h1>
<% @students.each do |student| %>
  <div>
    <%= link_to student, students_path(student) %> - <%= student.house %>
<% end %>
  </div>

app/views/students/new.html.erb
<h1>Welcome to the Sorting Hat!</h1>
<% image_tag "http://flavorwire.files.wordpress.com/2009/06/sorting-hat.jpg" %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<h2><%= @student.house %></h2>
<div class="student">
  <%= image_tag @student.img_url />
</div>